apiVersion: v1
kind: PersistentVolume
metadata:
  name: nlp-fulltext-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: /mnt/data/nlp-fulltext
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nlp-fulltext-pvc
  namespace: csearch-nlp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
