apiVersion: v1
kind: Secret
metadata:
  name: csearch-nlp-secrets
  namespace: csearch-nlp
type: Opaque
stringData:
  pg-connection-string: "postgresql://postgres:postgres@postgres-service.default.svc.cluster.local:5432/csearch"
  embedding-api-key: "ollama-local"
  llm-api-key: "ollama-local"
