apiVersion: v1
kind: Secret
metadata:
  name: csearch-nlp-secrets
  namespace: csearch-nlp
type: Opaque
stringData:
  pg-connection-string: "postgresql://csearch:_vchDeOmtjf1LOELSfvdoQ-H9MZoSXag@postgres.default.svc.cluster.local:5432/csearch"
  embedding-api-key: "ollama-local"
  llm-api-key: "ollama-local"
  openai-api-key: "REDACTED"
